### ISSUE TITLE
setup initial content for expression of interest

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/partnerships#35]
- Setup account on safe
- Project description
- Outline benefit to Safe ecosystem

**Comment by 0x4007** [comment]
> Setup account on safe

We have some Safes. Can you elaborate?

**Comment by Hodlatoor** [comment]
had to set up an account on the safe community forum as part of the
process.

**Comment by Hodlatoor** [comment]
https://safe-global.notion.site/Safe-Grants-7a14a7403f1f44f0bfb236a7521dac91 expression of interest was submitted.

**Comment by 0x4007** [comment]
> https://safe-global.notion.site/Safe-Grants-7a14a7403f1f44f0bfb236a7521dac91 expression of interest was submitted.

> - Setup account on safe
> - Project description
> - Outline benefit to Safe ecosystem 

I think in this case it would have made sense to open a pull request with a markdown document for proof on these, and have a reviewer (me) approve of the deliverable and mark this as completed. 

I think it's very unusual for somebody to write a bounty and claim it without a review. Otherwise it's too exploitable. 

It's also useful to use this repository as the information hub for all future contributors performing similar functions (e.g. @diamondnegroni). Like a centralized document with our messaging.

**Comment by Hodlatoor** [comment]
I agree. Reasonable points. Problem was I did this at the airport on my phone and realized i should have taken the screenshots after the fact.

**Comment by 0x4007** [comment]
What does SC mean? 

I also suggest not using acronyms because not everybody is a native English speaker lol

**Comment by Hodlatoor** [comment]
lol yes - edited the original message.

**Comment by 0x4007** [comment]
You can still open a pull request with a markdown document with all of this information and associate it to this issue.

**Comment by Hodlatoor** [comment]
is notion deleted? I know we stopped using it but it was working up until a few days ago. I had some of the copy-paste items for this there as well as some other centralized content.

**Comment by Hodlatoor** [comment]
trying alternate wallet after showing blank error msg on prev one.

**Comment by Hodlatoor** [comment]
still blank error message.

**Comment by 0x4007** [comment]
> is notion deleted? I know we stopped using it but it was working up until a few days ago. I had some of the copy-paste items for this there as well as some other centralized content.

I stopped sharing my workspace. I assume I still have the content on my workspace but I'm not sure what you're referring to.

We updated the dApp but didn't roll out the deployment yet because some feature needs to be rolled out at the same time on the bot. 

Here's the latest deployment that I could pull up, but it shouldn't be claimed or marked as completed until you have the deliverable associated.

https://pay.ubq.fi?network=100&claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNjE5NjA1NTk0NDA2OTE1NDQ5MDQxODg3MzM5MzEwMDYxMjYyOTA4MTc2NDM0NTY5MjYzMzg1MDEwMjU4ODUwMDE1NDc0NzQ1NTQ2MzAiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDVjNzQ3YjgzZjM0M0Y2NDJBRDk4M2UzQ2JlYTA0RkViMzcyMjdEZmUiLCJyZXF1ZXN0ZWRBbW91bnQiOiIyMDAwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDU0MTM3ZDM5ZTIzMmFlOTkzMTk1Mjc3Y2MwNzM1YjhkMmFiMDNmZTllOTkyMDE3NTIzZGM2ZWVmYTk1NmNlNTYyZDFiY2JiZmEyMDZiOGEwYzQzOWJlZmVlN2MwOTMzOTE3NDczNmM0OWJjYzc2ODA5OTE3M2QyNjEzZjgyYzUxMWMifQ==

**Comment by Hodlatoor** [comment]
Screen shot proof. readded what i could from the original app/saved in browser into the form. submitted last week as originally stated.

**Comment by Hodlatoor** [comment]
Screen shot proof. readded what i could from the original app/saved in browser into the form. submitted last week as originally stated.
![safe intent](https://github.com/ubiquity/business-development/assets/121923660/9b3c3685-73f7-418f-854b-3ce2671a71df)
