### ISSUE TITLE
Bounty proposal: Content for requests to Safe ecosystem foundation

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/partnerships#50]
Previously it was agreed that I will compile the content for requests to the Safe ecosystem foundation to apply here
https://notionforms.io/forms/get-in-touch-with-the-safe-ecosystem-foundation

Topics for requests
1. Safe to provide bounties for DevPool
2. Ubiquity to create a Dapp to the Safe marketplace
- The grant topic is discussed separately, so it should not be included in these topics.

Questions
- COMPANY/DAO/PROJECT NAME
- COMPANY/PROJECT WEBSITE 
- PLEASE TELL US IN DETAIL WHAT YOUR PROJECT DOES, WHAT YOU WANT TO DO WITH THE SAFE, AND WHERE THE CORE CONTRIBUTORS CAN HELP (150 CHARACTERS MINIMUM) 

The initial discussion https://github.com/orgs/ubiquity/projects/24/views/4?pane=issue&itemId=31314735

**Comment by sergfeldman** [comment]
This task is for 1 day

**Comment by Hodlatoor** [comment]
@pavlovcik @sergfeldman I already submitted this 5 days ago. ???

**Comment by 0x4007** [comment]
Normally only the first time the task was completed will it be marked as complete - but also requires the deliverables to be associated. Seems that redundant work was done, but it isn't clear to me if there is a redundant bounty.

@Hodlatoor can you link the redundant task?

**Comment by Hodlatoor** [comment]
So to clarify, It looks like Safe has some redundant forms.

What I applied for is the statement of interest. SAFE integration to users and PMs on devpool, as a small grant, $13k being the target. To get the product fully onboarded and the relationship marquee.  I finished this last week:
https://github.com/ubiquity/business-development/issues/35#issuecomment-1628331023
We are still waiting on them to open up the full grant but they have not so far. We need them to open this up so we can submit their full spec application. 

What @sergfeldman seems to have filled out is a different form which goes to SAFE's github.  Doesn't hurt but not sure where it will go. Might as well keep both. 

To emphasize again - My approach was a simple and cheap grant because their funds are limited. I wanted a "simple approval".  What @sergfeldman submitted is going to be a larger scope for them to review because it includes the card component which we have yet to have finalized internally.

**Comment by 0x4007** [comment]
> What I applied for is the statement of interest. 

I suggest making a special effort to make your task specifications as clear as possible, in this case by titling them with exactly the same title that Gnosis refers to them as, and with links to the correct landing and submission pages. 

Anybody else working on business development will have more clarity on what was worked on.

> https://github.com/ubiquity/business-development/issues/35#issuecomment-1628331023

I appreciate the screenshot proof. It could be more effective for realtime team collaboration if the screenshot/proof is posted right away upon task completion. 

> What @sergfeldman seems to have filled out is a different form which goes to SAFE's github. Doesn't hurt but not sure where it will go. Might as well keep both.

Reaching out on all of their available channels should increase our chances of conversion.

> To emphasize again - My approach was a simple and cheap grant because their funds are limited. I wanted a "simple approval".

Makes sense I think its a good idea.

---

As a side note: I have a feeling that it only makes sense to make bounties on deliverables like the content for the submissions. The actual submission process itself, unless its on GitHub in the form of a pull request like with W3F, I think its a bit awkward to prove. 

Documents are searchable and workable, and make sense to submit via a pull request to our team's repository. Perhaps the DevPool flow is only really useful for collaborative projects (e.g. editing and reviewing a markdown document) vs single person projects (submitting a web form.)

A screenshot works as a workaround, but seems not very elegant because we won't keep that in the repository (so we can't submit it via a pull request and go through the standard review process.) 

So it only makes sense to post in a comment, but then we can't do the standard review process. 

But I fear that screenshots would mostly clutter the repository if submitted as a pull request and saved in the repository.

**Comment by 0x4007** [comment]
@sergfeldman you state that you believe this is not a redundant task [here](https://github.com/ubiquity/business-development/issues/38#issuecomment-1630629919). 

Please explain to @Hodlatoor 

My apologies it seems that I closed this prematurely.

**Comment by sergfeldman** [comment]
@Hodlatoor 

### Main idea
Alex considers Safe a highly valuable partner.
Then we should look for all the ways to partner with Safe.
Several ways can operate in parallel, not only grant. 

### Details
Previously, we discussed the following options for cooperation:

**- Grant from Safe**
The essence is "Give us money for building something valuable"
We should follow the steps for the Safe Foundation grants.
Jon is leading and has cool ideas. 

**- Safe solves issues through DevPool**
The essence is "Use DevPool to develop the Safe ecosystem".
We need to communicate with the ones who make such decisions - the repo leads or CTO.
Currently, it seems that it is better to discuss this topic separately from the usual grant. 
I have collected some information about the Gnosis technical leads to the issue
- https://github.com/ubiquity/business-development/issues/57
So far, no one is leading this stream of business development. 

**- We create an application in the Safe marketplace**
I offered the message "Let's create a new product TOGETHER".
For this proposal we need to communicate with the one who makes such decisions - probably one of the founders.
It is an open question whether it is worth discussing now or later.
I defined the initial features in the PR
- https://github.com/ubiquity/business-development/pull/51
So far, no one is leading this stream of business development.

**- There may be other options for cooperation**
For example, create a Ubiquity Pay application in the Safe marketplace (independently from Safe). 
The Ubiquity Pay functionality will require users` GitHub handle and Gnosis wallet address for registration.
The application will allow transferring funds on the Gnosis Chain to other GitHub handles.
If it gets interest, the abilities can be extended with all major social networks and all major EVM blockchains and L2.
Also, it can be developed as "fiat & crypto payout infrastructure to withdraw directly to you bank account" like https://www.r3vl.xyz/#Protocol

**Comment by Hodlatoor** [comment]
@pavlovcik @sergfeldman maybe we want to look at https://github.com/ubiquity/research/issues/31 again and define components that build it as mini-tools which can be used for cooperation opportunities like a payout application?

**Comment by sergfeldman** [comment]
> @pavlovcik @sergfeldman maybe we want to look at [ubiquity/research#31](https://github.com/ubiquity/research/issues/31) again and define components that build it as mini-tools which can be used for cooperation opportunities like a payout application?

The main point that I wanted to communicate is that we should look for all the possibilities of cooperation with Safe, not only a Safe grant.
In this context, of course, it is worth considering Prometheus Engine as one of the directions :)

**Comment by sergfeldman** [comment]
One more option for collaboration with Gnosis.

>Gnosis is also launching Gnosis Pay, a set of developer tools that allow crypto wallets to create a version of their Gnosis Card for users without having to jump through all the hoops of building an online payments system.
https://techcrunch.com/2023/07/17/gnosis-has-a-visa-card-that-lets-you-spend-self-custodial-crypto-in-europe-soon-us-and-hong-kong/

**Comment by Hodlatoor** [comment]
https://www.theblock.co/post/157050/gnosis-safe-raises-100-million-led-by-1kx-as-it-rebrands-to-safe

also interesting to note that they spun out from gnosis and the $100m valuation

**Comment by sergfeldman** [comment]
>did you guys already fill out the forms on the gnosis.builders website? https://www.gnosis.builders/developers
>ok new rule. for something that quick like a form intended to start a conversation: just run and gun we’ll correct details on the call

@pavlovcik In the PR linked to this issue, I suggested filling out the 2 forms on this site and provided content for this. 
The review stretched for a long time.

The goal of the task was to compile content for requests.
The content was provided in the PR. After you announced the new rule, I filled out the forms. 

Please, decide whether this bounty has been completed or not.

**Comment by sergfeldman** [comment]
Waiting for the decision on this bounty

**Comment by 0x4007** [comment]
Hey @sergfeldman my apologies for the slow review. It hasn't been easy for me to be on GitHub these days.

**Comment by sergfeldman** [comment]
Thank you, claimed
