### ISSUE TITLE
Buidlbox partnership

### ISSUE THREAD

**Issue by Draeieg** [ubiquity/partnerships#66]
Buidlbox is now taking over gitcoin bounties as [mentioned](https://github.com/ubiquity/research/issues/69) by @sergfeldman 

I got the emails and talked to some of their team when we sponsored the hackathon, sent an email to their lead to see what can we get

<img width="475" alt="image" src="https://github.com/ubiquity/business-development/assets/88983138/0d2ca9f6-08a7-4259-b0e5-2ccc86d4564d">

**Comment by Draeieg** [comment]
@pavlovcik seems like we should disable time limits for this styile of tasks, since the time it takes us is not directly controlled by the hunter since there is a wait time from the other person we're shilling to

**Comment by 0x4007** [comment]
I understand your concern but instead of rearchitecting the system we can consider increasing the time over time to fund it more? 

I'm not totally sure what the best approach is. 

Lastly it is a good idea to define a deliverable that can be delivered as a pull request in order to standardize all of the tasks across the system, as well as allow for simple auditing by anyone in the future

---

We could also consider giving a max time like 1 day or 1 week of work input (I.e. 8 or 40 hours) before it's deemed not worth it anymore. 

Lastly there's the possibility of retroactive bounties aka sales commission aka evaluating afterwards. 

--- 

I'm thinking the wisest thing to do from a scalability standpoint: spend some days on researching the next quarter of outreach initiatives, then you can batch them in a meta issue and fire away on the work in series. You can also recruit other bizdevs to help knock them all out and collect your issue creator, and comment incentives.

**Comment by 0x4007** [comment]
I think I can also increase the base rate for this repo when I get to my computer.
