### ISSUE TITLE
IQ Wiki Updates

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/partnerships#84]
https://iq.wiki/wiki/ubiquity-dao/
https://t.me/sn0w_es has been following up with me but the info is very far out of date. Perhaps you can manage this being updated.

The idea is to get Ubiquity DAO on the "wikipedia of crypto"

**Comment by 0x4007** [comment]
@ana-0k

**Comment by ana-0k** [comment]
Fixed the article as I see fit the current situation, however, I didn't change anything in tokens/tokenomics part, cuz i'm not sure which ones you still intend to use.
Wouldn't it be better to just remove each token descriptions? Seems a bit too detailed for a wiki page
Also lmk if any other parts need changing.

-----------------------
**OVERVIEW**
Ubiquity DAO, founded in November 2020, is a decentralized autonomous organization focused on developing UbiquityOS — an AI-powered superintendent and surrounding infrastructure designed to increase the efficiency of DAO operations and advance open-source careers.
A key feature of the Ubiquity DAO ecosystem is integration of UUSD stablecoin and a blockchain-based payment system for instant reward claims on completed tasks, with the connection to real-world assets via Ubiquity payment Cards.
For engineers, UbiquityOS offers a seamless way to contribute to projects securely and independently of location and hiring restrictions, fostering the ideals of a truly decentralized world.

**Use Cases**
UbiquityOS aims to enhance efficiency for various users:
- **For Developers:** provides opportunities to work on preferred projects or get instantly matched with tasks suited to their skills, and provides financial incentives for completed work.
- **For Repository & Project Managers:** automates management, enables dynamic task pricing and scheduling to facilitate efficient completion, and provides an integrated payout system.
- **For DAOs:** Uses AI and custom-developed algorithms to streamline task assignment and boost overall organizational efficiency.

**PRODUCTS**
**UbiquityOS**
UbiquityOS aims to enhance organizational efficiency by integrating AI with GitHub and crypto payments, streamlining task management and project delivery. The system employs advanced content evaluation algorithms built on top of cutting-edge AI developments, currently achieving nearly 100% accuracy in managing coding-related tasks.
Additionally, UbiquityOS fully automates repetitive tasks, facilitates job matching, offers financial incentives for developers, and provides a more efficient, results-based payment system for organizations.
For the purpose of more precise task management and contribution tracking, UbiquityOS can be linked to other platforms such as Telegram, Google Docs, Slack and others.

**Ubiquity Dollar**
Ubiquity DAO's primary product is the Ubiquity Dollar (UUSD), a fully collateralized stablecoin designed with mechanisms that aim to maintain its $1 peg by adjusting supply based on market conditions. When UUSD's price exceeds $1, new UUSD is minted and distributed; if it drops below $1, holders can exchange UUSD for Ubiquity Credits (UCR), which are redeemable when the price stabilizes.

**Ubiquity Cards**
UbiquityDAO introduces Ubiquity Cards, starting with prepaid Mastercard and Visa options, which allow users to spend earnings from UbiquityOS. These virtual cards, compatible with Apple Pay, Google Pay, and Samsung Pay, do not require KYC for transactions up to $1,000 USD, making them accessible for users who value privacy or lack traditional banking services.
Future plans include Ubiquity Debit cards, which aim to support automatic balance top-ups from UbiquityOS earnings. This development will involve higher regulatory compliance and operational costs. Additionally, there is research into creating a lending market for credit based on Ubiquity governance tokens and Ubiquity Dollars.

**Ubiquity Wallet**
The Ubiquity Wallet aims to integrate with UbiquityDAO’s payment systems, including UbiquityOS and payment cards. As of March 2024, it is in early development for a browser extension and mobile apps for iOS/Android. The Wallet focuses on security and efficient user experience, with planned features such as live reward payout estimates and user XP stats on GitHub. A public beta of the browser extension is projected for the end of 2024.

**DevPool with Open Work Directory**
DevPool is a component of UbiquityOS that seeks to connect developers with projects by offering incentives and optimizing task assignment to enhance project outcomes and developer participation.
The UbiquityDAO DevPool aims to simplify contributions through defined guidelines. The system is based on GitHub, however, special UI can be created depending on client needs. Tasks should be self-assigned by opening draft pull requests.
To join the Ubiquity DevPool, locate tasks on [work.ubq.fi](http://work.ubq.fi/), commit to solving the issue by commenting your “/wallet [address]” for your first task in order to register your wallet for payouts, and simply /start for any following tasks. Before starting to work on the issue, seek clarifications if needed. After that, you should fork the repository, make regular commits, and mark your pull request for review. Payment links are provided after each successful task completion.

**TOKENOMICS**
**$uAD** (currently UUSD)
The Ubiquity Algorithmic Dollar (uAD) is a stablecoin aimed at maintaining a $1 value. When uAD's price rises above $1, the protocol mints additional uAD to bring the price down. Conversely, when the price falls below $1, holders can burn uAD for Ubiquity Credits (uCR), which are redeemable when the price recovers, in an effort to stabilize the value of uAD.

**$UBQ**
The UBQ token facilitates governance within the Ubiquity DAO. Initially, UBQ had no supply but is generated as users interact with Ubiquity's products. As an inflationary token, UBQ is minted to encourage adoption and enhance product functionality. To manage potential hyperinflation, a penalty is applied to the issuance of new tokens based on the total supply.
Additionally, UBQ is used in liquidity provisions, where funds are allocated to buy back tokens and provide liquidity in the Ubiquity markets.

**$uCR NFT**
The uCR NFT is an ERC-1155 token designed to support uAD's price stability. When the price of uAD falls below $1, holders can burn uAD to receive uCR NFTs, which can be redeemed for uAD at $1 when the price increases. These coupons, issued at a premium and valid for 180 days, can also be traded on secondary markets. The premium aims to encourage the burning of uAD, thereby assisting in managing its supply.

**$uCR**
uCR (Ubiquity Credit) is a mechanism used during debt cycles when the price of uAD falls below $1. Participants can burn uAD to receive uCR, which can be redeemed 1:1 for uAD when its price exceeds $1. uCR is issued with a premium that depreciates over time, aiming to encourage early redemption and stabilize uAD.
Unlike uCR NFTs, uCR does not expire but its redemption value decreases as the debt cycle progresses. This system aims to manage uAD's supply and maintain its price stability.

**Treasury**
The Treasury aims to support the development and enhancement of Ubiquity products. It is funded by contributions from products within the ecosystem, such as UUSD, which allocates a portion of its seigniorage. During periods when UUSD is the sole product, the Treasury’s funds are intended to provide liquidity for UUSD.
Initially managed by a multisig wallet, the Treasury's usage will transition to governance oversight after the prototype phase.

**Governance**
Ubiquity DAO governance operates in four phases:
- Rapid Prototyping: The team manages development and funding with uCR tokens, allowing for quick adjustments.
- Cool Off: Community feedback is gathered on proposed changes before implementation.
- Fully Decentralized Governance: Involves a Temperature Check to gauge interest, a Consensus Check for formal discussion and voting, and a Tender for proposal submission and review.
- Governance Proposal: Includes drafting, auditing, and voting on proposals, with a two-day timelock before implementation. Proposals may be revised and resubmitted if initially unsuccessful.

**Comment by 0x4007** [comment]
You only need to do this once but for unrelated reasons we might clear the database in the coming weeks and you might need to set it one more time

**Comment by ana-0k** [comment]
> Fixed the article as I see fit the current situation, however, I didn't change anything in tokens/tokenomics part, cuz i'm not sure which ones you still intend to use. Wouldn't it be better to just remove each token descriptions? Seems a bit too detailed for a wiki page Also lmk if any other parts need changing.

Hey @0x4007  lmk what you think about removing the token-related content ($uAD, $UBQ, $uCR NFT, $uCR)?
And generally if the updated text version above seems correct.
+saw that you want to rename uAD to UUSD and replaced it in the text beforehand (might be inconvenient to make additional changes to wiki later)

**Comment by 0x4007** [comment]
I'll help edit when I get wifi from my computer. Personal hotspot isn't working.

**Comment by 0x4007** [comment]
## Ubiquity DAO

Ubiquity DAO is a decentralized autonomous organization (DAO) founded in November 2020. It focuses on developing UbiquityOS, an AI-powered, organization superintendent designed to enhance the efficiency of DAO operations and promote open-source careers. A key feature of the ecosystem is the integration of the Ubiquity Dollar (UUSD), an Ethereum-based stablecoin used for instant reward claims on completed tasks, with support for off-ramping via Ubiquity Payment Cards.

## Ecosystem

### UbiquityOS

UbiquityOS integrates artificial intelligence with platforms like GitHub and crypto payments to streamline task management and project delivery. The system employs advanced content evaluation algorithms based on the latest in AI developments to manage coding-related tasks with high accuracy. It automates repetitive tasks, facilitates job matching, offers financial incentives for developers, and provides an efficient, results-based payment system for organizations. UbiquityOS can also connect with platforms such as Telegram, Google Docs, and Slack for precise task management and contribution tracking.

For contributors, UbiquityOS offers a seamless way to contribute to projects securely and independently of location and hiring restrictions, fostering the ideals of a truly decentralized world.

### Ubiquity Cards

Ubiquity Cards, leveraging the Mastercard and Visa payment networks, allow users to conveniently spend earnings from UbiquityOS. These cards are compatible with Apple Pay, Google Pay, and Samsung Pay and do not require Know Your Customer (KYC) procedures for balances up to $1,000 USD, making them accessible to new users who value privacy or lack traditional banking services. Research is also underway to integrate first-class support of a credit market based on Ubiquity Governance Tokens (UBQ) and Ubiquity Dollars (UUSD.)

### UbiquityOS Browser Extension

The Browser Extension is designed to integrate our augment our management and financial infrastructure on the client side. It focuses on security and user experience, with capabilities such augmented UI overlaid on any integrated website (like GitHub) like live reward payout estimates, Superintendent chatbox, and user experience points (XP) statistics. A public beta is projected for release by early 2025.

### Ubiquity DevPool

The Ubiquity DevPool is the shared DAO talent pool that UbiquityOS leverages to connect developers with tasks across all partner organizations. The system is based on GitHub and Telegram, but can be customized with specialized interfaces depending on partner needs. Developers can self-assign tasks by opening pull requests. To join the DevPool, developers locate tasks on the [devpool.directory](https://devpool.directory/), register their wallet for payouts by commenting `/wallet <wallet address>` on their first task, and start subsequent tasks by commenting `/start`. Developers fork the repository, make regular commits, and submit pull requests for review. Payment links are provided immediately after each successful task completion.

## Tokenomics

### Ubiquity Dollar (UUSD)

The Ubiquity Dollar (UUSD) is a 95% fully collateralized stablecoin designed to maintain its $1 peg through market-driven supply adjustments. When UUSD's price exceeds $1, users are incentivized to mint new UUSD by depositing $1 worth of LUSD (the underlying collateral) and selling the newly minted UUSD on the market, offering an arbitrage opportunity to restore the peg. Conversely, when UUSD's price falls below $1, users can purchase UUSD off of the open market at a discount and redeem it for $1 worth of LUSD, also offering an arbitrage opportunity to restore the peg.

### UBQ Token

The UBQ token represents ownership shares of Ubiquity DAO. This is planned to be used in conjunction with XP calculations to determine governance authority. It also can benefit from DAO profits as a portion is used to buy back and LP UBQ tokens off of the market, pushing up the price of the asset. Lastly, credit systems are planned to be built on top of UBQ tokens, allowing for the creation of a credit markets which integrate with Ubiquity Cards for spending convenience.

**Comment by 0x4007** [comment]
I think lets just submit this and then iterate later.

**Comment by 0x4007** [comment]
Unfortunate timing for your first payout because we are rushing to ship Ubiquity Cards into production and its part of why the claims are broken! Standby for just before GitHub Universe... 

Just remember that this claim stays valid so you can come back to it when things are up and running again. All the data is stored inside of the GitHub comment.

**Comment by 0x4007** [comment]
@gentlementlegen check out ana's formatting score. 

`50.63 * 0.9 = 45.567` 

Looks short changed by `33.91025`

I'm assuming this is config related but we should offer transparency on multipliers in the statistics table. RFC

**Comment by gentlementlegen** [comment]
The two non-displayed values are the `^0.85` and the `0.25` multiplier (due to external contributor). We can display them in the formatting column probably.

**Comment by 0x4007** [comment]
@gentlementlegen @whilefoo @keyrxng 

can you look at this openai error

This shouldn't occur in production
